DROP TABLE IF EXISTS `person`;
CREATE TABLE `person` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`name` varchar(20)DEFAULT NULL,
`age` int(11)DEFAULT NULL,
`nation` varchar(20)DEFAULT NULL,
`address` varchar(20)DEFAULT NULL,
PRIMARY KEY(`id`)
)ENGINE = InnoDB AUTO_INCREMENT = 51 DEFAULT CHARSET = utf8
;